# Generated by Django 4.0.3 on 2022-06-13 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('links', models.CharField(blank=True, default='{}', max_length=1000)),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='media/1.jpeg', upload_to=images.models.upload_to, verbose_name='Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=100)),
                ('expiration_time', models.DateTimeField()),
                ('image', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_token', to='images.image')),
            ],
        ),
    ]
