# Generated by Django 4.0.3 on 2022-06-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='extension',
        ),
    ]
