# Generated by Django 4.0.3 on 2022-06-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_image_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link_token',
            name='expiration_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
