# Generated by Django 4.0.3 on 2022-06-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_link_token_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link_token',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link_token',
            name='token',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
